language: node_js
cache:
  directories:
    - travis_phantomjs
before_install:
install : 
  - nvm install 8.11.1
  - nvm use 8.11.1
  - npm install
script:
  - node src/server.js & sleep 4 &
  - env TEST_EMAIL=$TEST_EMAIL TEST_PASSWORD=$TEST_PASSWORD API_KEY=$API_KEY TEST_PASSWORD2=$TEST_PASSWORD2 mocha test/mochaTest.js --exit
  - env TEST_EMAIL=$TEST_EMAIL TEST_PASSWORD=$TEST_PASSWORD API_KEY=$API_KEY TEST_PASSWORD2=$TEST_PASSWORD2 mocha test/CourseTest.js --exit
  - node test/Puppeteer_Regression.js
after_success:
  - process.exit()
  - echo Build Succeded